import React from "react";

import Grid from "@mui/material/Grid";
import { client } from "@/app/lib/sanity";
import { urlFor } from "@/app/lib/sanityImageUrl";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import Avatar from "@mui/material/Avatar";
import ArrowBackIosNewOutlinedIcon from "@mui/icons-material/ArrowBackIosNewOutlined";
import ArrowForwardIosOutlinedIcon from "@mui/icons-material/ArrowForwardIosOutlined";
import Box from "@mui/material/Box";
import "bootstrap/dist/css/bootstrap.min.css";

import Divider from "@mui/material/Divider";
// import { Helmet } from "react-helmet";
import Link from "next/link";

async function getData() {
  const query = `*[_type == "skill"]`;

  const data = await client.fetch(query);

  return data;
}
export const metadata = {
  title: "My Skills - Sufian Mustafa",
  description: "Generated by create next app",
};

export default async function IndexPage() {
  const data = await getData();

  const Item = {
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: "16px",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",

    border: "1px solid rgba(255, 255, 255, 0.3)",
  };
  const progress = {
    width: "90%",
    marginRight: "15px",
  };
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  ></link>;
  return (
    <div style={{ marginTop: "70px" }}>
      <>
        <style type="text/css">
          {`   

.progress-bar{  background-color:  rgba(78, 78, 246, 0.647); 
  border-radius:20px;
font-size:17px;
color:black; }
.progress{
background-color: rgba(247, 90, 216, 0.696);
border-radius:20px;
}


}

`}
        </style>
      </>
      <div>
        <Grid
          container
          spacing={2}
          padding={2}
          sx={{
            display: "flex",
            textAlign: "center",
            justifyContent: "center",
          }}
        >
          <Grid item lg={9} sm={12} style={{ width: "100%" }} className="flex">
            <div style={{ width: "100%" }} className="item">
              <div className="about41" style={{ overflow: "hidden" }}>
                <h3>
                  <span style={{ float: "left" }} className="HeadingArrow">
                    <ArrowBackIosNewOutlinedIcon />
                    <ArrowBackIosNewOutlinedIcon />
                  </span>
                  My Skill
                  <span style={{ float: "right" }} className="HeadingArrow">
                    {" "}
                    <ArrowForwardIosOutlinedIcon />
                    <ArrowForwardIosOutlinedIcon />
                  </span>
                </h3>
              </div>
              <div className="About3">
                <p>
                  {" "}
                  In my journey as a developer, I have gained proficiency in a
                  variety of technologies and tools. Below, you will find an
                  overview of my skills, each accompanied by a percentage that
                  reflects my level of expertise.
                </p>
              </div>
              <Box>
                <List sx={{ overflowX: "visible", width: "100%" }}>
                  {data.map((skill) => (
                    // eslint-disable-next-line react/jsx-key
                    <Link
                      href={`/skill/${skill.slug.current}`}
                      prefetch
                      style={{ textDecoration: "none" }}
                    >
                      <ListItem key={skill._id} className="SkillList">
                        <ListItemAvatar>
                          <Avatar
                            style={{
                              background: "none",
                              backgroundSize: "cover",
                              backgroundPosition: "center",
                              width: "60px", // Adjust the width as needed
                              height: "60px", // Maintain a square aspect
                            }}
                          >
                            <img
                              className="i-swing"
                              src={urlFor(skill.skillimg).url()}
                              alt=""
                              style={{ width: "100%", height: "auto" }}
                            />
                          </Avatar>
                        </ListItemAvatar>

                        <div className="progress" style={{ width: "100%" }}>
                          <div
                            className="progress-bar progress-bar-striped progress-bar-animated"
                            style={{ width: `${skill.percentage}%` }}
                          >
                            <span className="progress-label-color">{`${skill.percentage}%`}</span>
                          </div>
                        </div>
                        <p> {"  "} </p>
                        <ListItemText
                          primary={skill.title}
                          style={{ width: "30%" }}
                          className="ListItemTextSkill"
                        />
                      </ListItem>
                    </Link>
                  ))}
                </List>
              </Box>
              <div className="About3">
                <p>
                  {" "}
                  My skills are not static; I am committed to continuous
                  learning and growth, which enables me to adapt to new
                  challenges and technologies effectively. As I evolve, I look
                  forward to elevating my expertise across all areas of
                  development. <br />
                  Feel free to reach out if you like to discuss my skills
                  further or if you have specific questions about any technology
                  mentioned above.
                </p>
              </div>
              <br />
            </div>
          </Grid>
        </Grid>
      </div>

      <br></br>
      <Divider />

      <br></br>
    </div>
  );
}
